### ISSUE TITLE
Release 2.6.0

### ISSUE THREAD

**Issue by BinToss** [adriens/chocolatey-codeql#2]
https://repology.org/project/codeql/versions
https://github.com/github/codeql-cli-binaries/releases/tag/v2.6.0

<html>
<div class="col-12 col-md-9 col-lg-10 px-md-3 py-md-4 release-main-section commit open float-left">
<div class="release-header">

<p class="f5 color-text-secondary mt-2 mt-md-1 mb-2 mb-md-4">
<a class="d-inline-block" data-hovercard-type="user" data-hovercard-url="/users/codeql-ci/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/codeql-ci"><img class="avatar avatar-user" src="https://avatars.githubusercontent.com/u/68440632?s=40&amp;v=4" alt="@codeql-ci" width="20" height="20"></a>
<a class="text-bold color-text-secondary" data-hovercard-type="user" data-hovercard-url="/users/codeql-ci/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/codeql-ci">codeql-ci</a>
released this
<relative-time datetime="2021-08-24T22:37:23Z" class="no-wrap" title="Aug 24, 2021, 3:37 PM PDT">11 days ago</relative-time>
</p>

</div>

<div class="markdown-body">
<p>The bundled extractors are updated to match the versions currently used on LGTM.com. These are newer than the last release (1.27) of LGTM Enterprise. If you plan to upload databases to an LGTM Enterprise 1.27 instance, you need to create them with release 2.4.6.</p>
<h3>Bugs fixed</h3>
<ul>
<li>
<p>The <code>physicalLocation.artifactLocation.uri</code> fields in SARIF output are now properly encoded as specified by RFC 3986.</p>
</li>
<li>
<p>The <code>--include-extension</code> option to the <code>codeql database index-files</code> command no longer includes directories that are named with the provided extension. For example, if the option <code>--include-extension=.rb</code> is provided, then a directory named <code>foo.rb/</code> will be excluded from the indexing.</p>
</li>
</ul>
<h3>New features</h3>
<ul>
<li>
<p>A new <code>codeql database unbundle</code> subcommand performs the reverse of <code>codeql database bundle</code> and extracts a CodeQL database from an archive.</p>
</li>
<li>
<p>The CLI now understands per-codebase configuration files in <a href="https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#example-configuration-files">the format already supported by the CodeQL Action</a>.</p>
</li>
<li>
<p>The CLI now supports the "sandwiched tracing" feature that has previously only been offered through the separate CodeQL Runner. This feature is intended for use with CI systems that cannot be configured to wrap build actions with <code>codeql database trace-command</code>.</p>
</li>
<li>
<p>This version contains <em>beta</em> support for a new packaging and publishing system for third-party QL queries and libraries.</p>
</li>
</ul>
<p>For more information about these new features, see the <a href="https://github.com/github/codeql-cli-binaries/blob/HEAD/CHANGELOG.md">CodeQL CLI changelog</a>.</p>
<p>You can download <em>either</em> the <code>codeql-PLATFORM.zip</code> for your platform, <em>or</em> the generic <code>codeql.zip</code> which contains binaries for all supported platforms. Please ignore the additional "source code" downloads below the <code>.zip</code> artifacts.</p>
</div>

<div class="d-flex flex-column flex-md-row flex-justify-between flex-content-center mb-n4 mt-4 border-top js-comment reactions-with-gap pb-3">
<div class="mt-3 ml-n3 comment d-flex">
<div class="comment-reactions d-flex flex-items-start flex-row-reverse js-reactions-container js-reaction-buttons-container flex-justify-end social-reactions">
<form class="js-pick-reaction" action="/github/codeql-cli-binaries/reactions" accept-charset="UTF-8" method="post"><input type="hidden" name="_method" value="put"><input type="hidden" name="authenticity_token" value="w0DUAYMS6fln8KzVZtTH0e54y2SFzbavOuIfcy4EvnzYw6rbwteByAWhX+M9h6Hf5Le7aLR/nEZ7z+8mpv0tIg==">
<input type="hidden" name="input[subjectId]" value="MDc6UmVsZWFzZTQ4Mzc5NzQ4">

<div class="comment-reactions-options js-comment-reactions-options">
</div>
</form>
</div>

</div>
</div>

<details class="details-reset Details-element border-top pt-3 mt-4 mb-2 mb-md-4" open="">
<summary>
<div class="d-flex flex-items-center">
<span class="mr-2 Details-content--closed"><svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-triangle-right">
<path d="M6.427 4.427l3.396 3.396a.25.25 0 010 .354l-3.396 3.396A.25.25 0 016 11.396V4.604a.25.25 0 01.427-.177z"></path>
</svg></span>
<span class="mr-2 Details-content--open"><svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-triangle-down">
<path d="M4.427 7.427l3.396 3.396a.25.25 0 00.354 0l3.396-3.396A.25.25 0 0011.396 7H4.604a.25.25 0 00-.177.427z"></path>
</svg></span>
<span class="text-bold">Assets</span>
<span title="6" data-view-component="true" class="Counter ml-1">6</span>
</div>
</summary>
<div class="Box Box--condensed mt-3">
<div>
<div class="d-flex flex-justify-between flex-items-center py-1 py-md-2 Box-body px-2">
<a href="/github/codeql-cli-binaries/releases/download/v2.6.0/codeql-linux64.zip" rel="nofollow" class="d-flex flex-items-center min-width-0">
<svg class="octicon octicon-package flex-shrink-0 color-text-secondary" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M8.878.392a1.75 1.75 0 00-1.756 0l-5.25 3.045A1.75 1.75 0 001 4.951v6.098c0 .624.332 1.2.872 1.514l5.25 3.045a1.75 1.75 0 001.756 0l5.25-3.045c.54-.313.872-.89.872-1.514V4.951c0-.624-.332-1.2-.872-1.514L8.878.392zM7.875 1.69a.25.25 0 01.25 0l4.63 2.685L8 7.133 3.245 4.375l4.63-2.685zM2.5 5.677v5.372c0 .09.047.171.125.216l4.625 2.683V8.432L2.5 5.677zm6.25 8.271l4.625-2.683a.25.25 0 00.125-.216V5.677L8.75 8.432v5.516z"></path></svg>
<span class="pl-2 flex-auto min-width-0 text-bold">codeql-linux64.zip</span>
</a>
<small class="pl-2 color-text-secondary flex-shrink-0">254 MB</small>
</div>
<div class="d-flex flex-justify-between flex-items-center py-1 py-md-2 Box-body px-2">
<a href="/github/codeql-cli-binaries/releases/download/v2.6.0/codeql-osx64.zip" rel="nofollow" class="d-flex flex-items-center min-width-0">
<svg class="octicon octicon-package flex-shrink-0 color-text-secondary" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M8.878.392a1.75 1.75 0 00-1.756 0l-5.25 3.045A1.75 1.75 0 001 4.951v6.098c0 .624.332 1.2.872 1.514l5.25 3.045a1.75 1.75 0 001.756 0l5.25-3.045c.54-.313.872-.89.872-1.514V4.951c0-.624-.332-1.2-.872-1.514L8.878.392zM7.875 1.69a.25.25 0 01.25 0l4.63 2.685L8 7.133 3.245 4.375l4.63-2.685zM2.5 5.677v5.372c0 .09.047.171.125.216l4.625 2.683V8.432L2.5 5.677zm6.25 8.271l4.625-2.683a.25.25 0 00.125-.216V5.677L8.75 8.432v5.516z"></path></svg>
<span class="pl-2 flex-auto min-width-0 text-bold">codeql-osx64.zip</span>
</a>
<small class="pl-2 color-text-secondary flex-shrink-0">207 MB</small>
</div>
<div class="d-flex flex-justify-between flex-items-center py-1 py-md-2 Box-body px-2">
<a href="/github/codeql-cli-binaries/releases/download/v2.6.0/codeql-win64.zip" rel="nofollow" class="d-flex flex-items-center min-width-0">
<svg class="octicon octicon-package flex-shrink-0 color-text-secondary" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M8.878.392a1.75 1.75 0 00-1.756 0l-5.25 3.045A1.75 1.75 0 001 4.951v6.098c0 .624.332 1.2.872 1.514l5.25 3.045a1.75 1.75 0 001.756 0l5.25-3.045c.54-.313.872-.89.872-1.514V4.951c0-.624-.332-1.2-.872-1.514L8.878.392zM7.875 1.69a.25.25 0 01.25 0l4.63 2.685L8 7.133 3.245 4.375l4.63-2.685zM2.5 5.677v5.372c0 .09.047.171.125.216l4.625 2.683V8.432L2.5 5.677zm6.25 8.271l4.625-2.683a.25.25 0 00.125-.216V5.677L8.75 8.432v5.516z"></path></svg>
<span class="pl-2 flex-auto min-width-0 text-bold">codeql-win64.zip</span>
</a>
<small class="pl-2 color-text-secondary flex-shrink-0">223 MB</small>
</div>
<div class="d-flex flex-justify-between flex-items-center py-1 py-md-2 Box-body px-2">
<a href="/github/codeql-cli-binaries/releases/download/v2.6.0/codeql.zip" rel="nofollow" class="d-flex flex-items-center min-width-0">
<svg class="octicon octicon-package flex-shrink-0 color-text-secondary" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M8.878.392a1.75 1.75 0 00-1.756 0l-5.25 3.045A1.75 1.75 0 001 4.951v6.098c0 .624.332 1.2.872 1.514l5.25 3.045a1.75 1.75 0 001.756 0l5.25-3.045c.54-.313.872-.89.872-1.514V4.951c0-.624-.332-1.2-.872-1.514L8.878.392zM7.875 1.69a.25.25 0 01.25 0l4.63 2.685L8 7.133 3.245 4.375l4.63-2.685zM2.5 5.677v5.372c0 .09.047.171.125.216l4.625 2.683V8.432L2.5 5.677zm6.25 8.271l4.625-2.683a.25.25 0 00.125-.216V5.677L8.75 8.432v5.516z"></path></svg>
<span class="pl-2 flex-auto min-width-0 text-bold">codeql.zip</span>
</a>
<small class="pl-2 color-text-secondary flex-shrink-0">542 MB</small>
</div>

<div class="d-block py-1 py-md-2 Box-body px-2">
<a href="/github/codeql-cli-binaries/archive/refs/tags/v2.6.0.zip" rel="nofollow" class="d-flex flex-items-center">
<svg class="octicon octicon-file-zip flex-shrink-0 color-text-secondary" width="16" height="16" viewBox="0 0 16 16" version="1.1" aria-hidden="true"><path fill-rule="evenodd" d="M3.5 1.75a.25.25 0 01.25-.25h3a.75.75 0 000 1.5h.5a.75.75 0 000-1.5h2.086a.25.25 0 01.177.073l2.914 2.914a.25.25 0 01.073.177v8.586a.25.25 0 01-.25.25h-.5a.75.75 0 000 1.5h.5A1.75 1.75 0 0014 13.25V4.664c0-.464-.184-.909-.513-1.237L10.573.513A1.75 1.75 0 009.336 0H3.75A1.75 1.75 0 002 1.75v11.5c0 .649.353 1.214.874 1.515a.75.75 0 10.752-1.298.25.25 0 01-.126-.217V1.75zM8.75 3a.75.75 0 000 1.5h.5a.75.75 0 000-1.5h-.5zM6 5.25a.75.75 0 01.75-.75h.5a.75.75 0 010 1.5h-.5A.75.75 0 016 5.25zm2 1.5A.75.75 0 018.75 6h.5a.75.75 0 010 1.5h-.5A.75.75 0 018 6.75zm-1.25.75a.75.75 0 000 1.5h.5a.75.75 0 000-1.5h-.5zM8 9.75A.75.75 0 018.75 9h.5a.75.75 0 010 1.5h-.5A.75.75 0 018 9.75zm-.75.75a1.75 1.75 0 00-1.75 1.75v3c0 .414.336.75.75.75h2.5a.75.75 0 00.75-.75v-3a1.75 1.75 0 00-1.75-1.75h-.5zM7 12.25a.25.25 0 01.25-.25h.5a.25.25 0 01.25.25v2.25H7v-2.25z"></path></svg>
<span class="px-1 text-bold">Source code</span> (zip)
</a>
</div>
<div class="d-block py-1 py-md-2 Box-body px-2">
<a href="/github/codeql-cli-binaries/archive/refs/tags/v2.6.0.tar.gz" rel="nofollow" class="d-flex flex-items-center">
<svg class="octicon octicon-file-zip flex-shrink-0 color-text-secondary" width="16" height="16" viewBox="0 0 16 16" version="1.1" aria-hidden="true"><path fill-rule="evenodd" d="M3.5 1.75a.25.25 0 01.25-.25h3a.75.75 0 000 1.5h.5a.75.75 0 000-1.5h2.086a.25.25 0 01.177.073l2.914 2.914a.25.25 0 01.073.177v8.586a.25.25 0 01-.25.25h-.5a.75.75 0 000 1.5h.5A1.75 1.75 0 0014 13.25V4.664c0-.464-.184-.909-.513-1.237L10.573.513A1.75 1.75 0 009.336 0H3.75A1.75 1.75 0 002 1.75v11.5c0 .649.353 1.214.874 1.515a.75.75 0 10.752-1.298.25.25 0 01-.126-.217V1.75zM8.75 3a.75.75 0 000 1.5h.5a.75.75 0 000-1.5h-.5zM6 5.25a.75.75 0 01.75-.75h.5a.75.75 0 010 1.5h-.5A.75.75 0 016 5.25zm2 1.5A.75.75 0 018.75 6h.5a.75.75 0 010 1.5h-.5A.75.75 0 018 6.75zm-1.25.75a.75.75 0 000 1.5h.5a.75.75 0 000-1.5h-.5zM8 9.75A.75.75 0 018.75 9h.5a.75.75 0 010 1.5h-.5A.75.75 0 018 9.75zm-.75.75a1.75 1.75 0 00-1.75 1.75v3c0 .414.336.75.75.75h2.5a.75.75 0 00.75-.75v-3a1.75 1.75 0 00-1.75-1.75h-.5zM7 12.25a.25.25 0 01.25-.25h.5a.25.25 0 01.25.25v2.25H7v-2.25z"></path></svg>
<span class="px-1 text-bold">Source code</span> (tar.gz)
</a>
</div>
</div>
</div>
</details>

</div>
</html>

**Comment by adriens** [comment]
https://community.chocolatey.org/packages/codeql/2.6.0

![image](https://user-images.githubusercontent.com/5235127/132141099-6ccd35cd-f81f-4939-adba-4877b49c1abe.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/132141860-bc37e077-0dbc-4f11-bf0e-de55c6485d9e.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/132142173-d490eb1a-fa60-4221-b211-88c881876c95.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/132271296-ae06d8a2-7cc5-450f-b30b-f9e908527478.png)

**Comment by adriens** [comment]
@BinToss :  Released 👏 🎆 
![image](https://user-images.githubusercontent.com/5235127/132603125-6d5d9a66-e1dd-416e-85d1-545b2be011d0.png)
